# Generated by Django 2.2.5 on 2019-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_auto_20190903_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionesClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('usuario', models.CharField(max_length=50, verbose_name='usuario')),
                ('imagen_usuario', models.ImageField(upload_to='clientes/', verbose_name='Imagen Referencial')),
                ('mensaje', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Opinion Cliente',
                'verbose_name_plural': 'Opiniones Clientes',
            },
        ),
    ]
