# Generated by Django 2.2.5 on 2019-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_opinionesclientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionesclientes',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='opinionesclientes',
            name='usuario',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
