# Generated by Django 2.2.5 on 2019-09-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0007_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
