# Generated by Django 2.2.5 on 2019-09-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0008_auto_20190904_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
    ]
