# Generated by Django 2.2.5 on 2019-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0010_desarrollador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='foto',
            field=models.ImageField(height_field='300', upload_to='desarrolladores/', verbose_name='Imagen Referencial', width_field='300'),
        ),
    ]
