# Generated by Django 2.2.5 on 2019-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0013_subscriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinionesclientes',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='opinionesclientes',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='opinionesclientes',
            name='fecha_eliminacion',
        ),
        migrations.RemoveField(
            model_name='opinionesclientes',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='opinionesclientes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
