# Generated by Django 2.2.5 on 2019-09-26 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0014_auto_20190926_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionesclientes',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='opinionesclientes',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinionesclientes',
            name='fecha_eliminacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='opinionesclientes',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='opinionesclientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
