# Generated by Django 2.2.5 on 2019-09-19 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190919_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_referencial',
            field=models.ImageField(max_length=255, upload_to='imagenes/', verbose_name='Imagen Referencial'),
        ),
    ]
