# Generated by Django 2.2.5 on 2019-09-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20190919_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='web',
        ),
    ]
