# Generated by Django 2.2.5 on 2019-09-12 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('roltipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autenticacion.Rol')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol Usuario',
                'verbose_name_plural': 'Roles Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoid', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía (CC)'), ('CE', 'Cédula de Extranjería (CE)'), ('DNI', 'Documento Nacional de Identidad (DNI)'), ('DUI', 'Documento Único de Identidad (DUI)')], default='CC', max_length=20, null=True)),
                ('numeroid', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(default='usuarios/usuario.png', upload_to='usuarios')),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Persona',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
    ]
