# Generated by Django 2.2.5 on 2019-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='genero',
            field=models.CharField(choices=[('M', 'Maculino (M)'), ('F', 'Femenino (F)'), ('O', 'Otro (O)')], default='M', max_length=20, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellido',
            field=models.CharField(max_length=50, null='True', verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='correo',
            field=models.CharField(max_length=50, null='True', verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(default='usuarios/usuario.png', upload_to='usuarios', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numeroid',
            field=models.CharField(max_length=20, null='True', verbose_name='Numero de identificacion'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono',
            field=models.CharField(max_length=20, null='True', verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='tipoid',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía (CC)'), ('CE', 'Cédula de Extranjería (CE)'), ('DNI', 'Documento Nacional de Identidad (DNI)'), ('DUI', 'Documento Único de Identidad (DUI)')], default='CC', max_length=20, verbose_name='Tipo Identificacion'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='roltipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de rol'),
        ),
    ]
