# Generated by Django 2.2.5 on 2019-09-27 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Autenticacion', '0002_auto_20190912_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, null='True', verbose_name='Apellido')),
                ('genero', models.CharField(choices=[('M', 'Maculino (M)'), ('F', 'Femenino (F)'), ('O', 'Otro (O)')], default='M', max_length=20, verbose_name='Genero')),
                ('tipoid', models.CharField(choices=[('CC', 'Cédula de Ciudadanía (CC)'), ('CE', 'Cédula de Extranjería (CE)'), ('DNI', 'Documento Nacional de Identidad (DNI)'), ('DUI', 'Documento Único de Identidad (DUI)')], default='CC', max_length=20, verbose_name='Tipo Identificacion')),
                ('numeroid', models.CharField(max_length=20, null='True', verbose_name='Numero de identificacion')),
                ('telefono', models.CharField(max_length=20, null='True', verbose_name='Telefono')),
                ('correo', models.CharField(max_length=50, null='True', verbose_name='Correo')),
                ('foto', models.ImageField(default='usuarios/usuario.png', upload_to='usuarios', verbose_name='foto')),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
