# Generated by Django 2.2.5 on 2019-09-27 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0003_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuid',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
