# Generated by Django 2.2.5 on 2019-09-28 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0004_auto_20190927_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='usuid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
