# Generated by Django 2.2.5 on 2019-09-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0008_vinculaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculaciones',
            name='cuidador',
        ),
        migrations.AddField(
            model_name='vinculaciones',
            name='cuidador_id',
            field=models.CharField(max_length=50, null='True', verbose_name='Cuidador_ID'),
            preserve_default='True',
        ),
    ]
