# Generated by Django 2.2.5 on 2019-09-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0009_auto_20190928_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculaciones',
            name='foto',
            field=models.ImageField(default='usuarios/usuario.png', upload_to='usuarios', verbose_name='foto'),
        ),
    ]
