# Generated by Django 2.2.5 on 2019-09-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0011_remove_vinculaciones_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculaciones',
            options={'verbose_name': 'Vinculación', 'verbose_name_plural': 'Vinculaciones'},
        ),
    ]
