# Generated by Django 2.2.5 on 2019-09-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0012_auto_20190928_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='pacientes/usuario.png', upload_to='usuarios', verbose_name='foto'),
        ),
    ]
