# Generated by Django 2.2.5 on 2019-09-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0013_auto_20190928_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='pacientes/usuario.png', upload_to='pacientes', verbose_name='foto'),
        ),
    ]
