# Generated by Django 2.2.5 on 2019-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0015_auto_20190928_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(upload_to='pacientes', verbose_name='foto'),
        ),
    ]
